[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/robostack-jazzy", 
  "pytorch"
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "booster_gym"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.host-dependencies]
hatchling = "*"
python = "==3.11"

[dependencies]
booster_gym = { path = "." }
pybind11 = ">=3.0.1,<4"
pybind11-stubgen = ">=2.5.5,<3"
ros-jazzy-fastrtps = ">=2.14.4,<3"
ros-jazzy-fastcdr = ">=2.2.5,<3"
foonathan-memory = ">=0.7.3,<0.8"
evdev = ">=1.9.2,<2"

[activation]
env = { PATH = "$CONDA_PREFIX/bin:$PATH", LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:$CONDA_PREFIX/lib", PYTHONPATH = "/usr/local/lib/python3.11/dist-packages:$PYTHONPATH" }

[pypi-dependencies]
fast_td3 = {git = "https://github.com/younggyoseo/FastTD3.git", branch = "main"}
setuptools = ">=59.0.0"
tensorboard = ">=2.10.0"
torch = ">=1.10.0"
pyyaml = ">=5.3.1"
imageio = ">=2.9.0"
wandb = ">=0.22.2, <0.23"
mujoco = ">=3.2.3, <4"
tensordict = ">=0.5.0, <0.6"
sshkeyboard = ">=2.3.1, <3"
